apiVersion: apps/v1
kind: Deployment
metadata:
  name: nk
  labels:
    app: nk
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nk
  template:
    metadata:
      labels:
        app: nk
    spec:
      containers:
      - name: nk
        image: node-kubernetes:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8855
---
apiVersion: v1
kind: Service
metadata:
  name: nk-service
spec:
  type: NodePort
  selector:
    app: nk
  ports:
    - port: 8855
      targetPort: 8855