apiVersion: apps/v1
kind: Deployment
metadata:
  name: nk
  labels:
    app: nk
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nk
  template:
    metadata:
      labels:
        app: nk
    spec:
      containers:
      - name: nk
        image: node-kubernetes:latest
        env:
        - name: DATABASE_URL
          value: postgresql://postgres:postgres@nk-postgres:5432/nk-postgres
        imagePullPolicy: Never
        ports:
        - containerPort: 8855
---
apiVersion: v1
kind: Service
metadata:
  name: nk-service
spec:
  type: NodePort
  selector:
    app: nk
  ports:
    - port: 8855
      targetPort: 8855
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nk-postgres
  labels:
    app: nk-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nk-postgres
  template:
    metadata:
      labels:
        app: nk-postgres
    spec:
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: postgres-vc
      containers:
      - name: nk-postgres
        image: postgres
        env:
        - name: POSTGRES_PASSWORD
          value: postgres
        - name: POSTGRES_DB
          value: pospospospos
        volumeMounts:
        - mountPath: "/var/lib/postgresql/data"
          name: postgres-data
        ports:
        - containerPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: nk-postgres
spec:
  type: ClusterIP
  selector:
    app: nk-postgres
  ports:
    - port: 5432
      targetPort: 5432
