apiVersion: apps/v1
kind: Deployment
metadata:
  name: nk
  labels:
    app: nk
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nk
  template:
    metadata:
      labels:
        app: nk
    spec:
      containers:
      - name: nk
        image: node-kubernetes:latest
        env:
        - name: DATABASE_URL
          value: postgresql://postgres:postgres@nk-postgres:5432/nk
        imagePullPolicy: Never
        ports:
        - containerPort: 8855
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-v
  labels:
    type: local
    app: postgres-v
spec:
  storageClassName: local
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/k8s"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-vc
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 8Gi
  storageClassName: local
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nk-postgres
  labels:
    app: nk-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nk-postgres
  template:
    metadata:
      labels:
        app: nk-postgres
    spec:
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: postgres-vc
      containers:
      - name: nk-postgres
        image: postgres
        volumeMounts:
        - mountPath: "/var/lib/postgresql/data"
          name: postgres-data
        env:
        - name: POSTGRES_PASSWORD
          value: "postgres"
        - name: POSTGRES_DATABASE
          value: "nk"
        ports:
        - containerPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: nk-service
spec:
  type: NodePort
  selector:
    app: nk
  ports:
    - port: 8855
      targetPort: 8855
