apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-v
  labels:
    type: local
    app: postgres-v
spec:
  storageClassName: local
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/k8s"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-vc
spec:
  storageClassName: local
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 8Gi
